export const EMAIL_CHANGED = "resonance/EVENT/SIGNIN/EMAIL_CHANGED"
export const PASSWORD_CHANGED = "resonance/EVENT/SIGNIN/PASSWORD_CHANGED"
export const RESET_PASSWORD = "resonance/COMMAND/RESET_PASSWORD"
export const PASSWORD_RESET_EMAIL_SENT =
  "resonance/EVENT/PASSWORD_RESET_EMAIL_SENT"
export const VERIFY_RESET_TOKEN = "resonance/COMMAND/VERIFY_RESET_TOKEN"
