export const EXPANSION_TOGGLED = "ACTION_HUB/EXPANSION_TOGGLED"
export const SUBMIT_IDEA_FORM = "ACTION_HUB/SUBMIT_IDEA_FORM"
export const UPDATE_FORM = "ACTION_HUB/UPDATE_FORM"
export const DESTROY_IDEA = "ACTION_HUB/DESTROY_IDEA"
