export const FETCH_IDEA = "IDEAS/FETCH_IDEA"
export const IDEA_RECEIVED = "IDEAS/IDEA_RECEIVED"
export const FETCH_ACTION_HUB_IDEAS = "ACTION-HUB/FETCH_IDEAS"
export const IDEAS_RECEIVED = "ACTION-HUB/IDEAS_RECEIVED"
