import React from "react"
import Typography from "material-ui/Typography"
import PostSlide from "../PostSlide"

export default props => {
  const { next, previous } = props
  return (
    <PostSlide next={next} previous={previous}>
      <Typography variant="body2" paragraph>
        The world we want to create has yet to unfold, but the building blocks
        are already here with us. They have been passed to us from our
        ancestors, and we will pass them to our descendants. We are recovering
        old ways of being, while innovating how those ways will manifest in the
        world of the future. Across many places, cultures, and peoples, the
        emerging worldview is expressing itself, and thus we seek to amplify the
        stories of the people and places living into that worldview.
      </Typography>
      <Typography variant="body2" paragraph>
        We invite you to join us in co-creating and experiencing this emerging
        worldview. Let us orient toward a common horizon.
      </Typography>

      <Typography variant="body2" paragraph>
        Here we highlight a few expressions of worldviews that were generated by
        different people, in different places, at different times.
      </Typography>
    </PostSlide>
  )
}
