export const FETCH_POSTS = "resonance/COMMAND/FETCH_POSTS"
export const POSTS_RECEIVED = "resonance/EVENT/POSTS_RECEIVED"
export const FETCH_POST = "LEARNING-HUB/FETCH_POST"
export const POST_RECEIVED = "LEARNING-HUB/POST_RECEIVED"
export const EDITOR_STATE_CHANGED = "LEARNING-HUB/EDITOR_STATE_CHANGED"
export const PERSIST_POST = "LEARNING-HUB/PERSIST_POST"
export const EDITOR_TITLE_CHANGED = "LEARNING-HUB/EDITOR_TITLE_CHANGED"
export const POST_PERSISTED = "LEARNING-HUB/POST_PERSISTED"
export const TAGS_RECEIVED = "LEARNING-HUB/TAGS_RECEIVED"
export const FETCH_TAGS = "LEARNING-HUB/FETCH_TAGS"
export const CATEGORY_SELECTION_CHANGED =
  "LEARNING-HUB/CATEGORY_SELECTION_CHANGED"
export const KEYWORD_SELECTION_CHANGED =
  "LEARNING-HUB/KEYWORD_SELECTION_CHANGED"
export const MEDIA_TYPE_SELECTION_CHANGED =
  "LEARNING-HUB/MEDIA_TYPE_SELECTION_CHANGED"
